server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://qweholccqjxihb:5aac6a9b870608ccf23ef52a6b519413ea2a65684a618dcbb16b530687d41769@ec2-54-160-96-70.compute-1.amazonaws.com:5432/d2j277ja33un9s
    username: qweholccqjxihb
    password: 5aac6a9b870608ccf23ef52a6b519413ea2a65684a618dcbb16b530687d41769
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend  
  version: 1.0